version: '3.8'

services:
  sales-report-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    volumes:
      # 데이터 영속화를 위한 볼륨 마운트
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/debug"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 